In [ ]:
!pip install numpy

In [ ]:
import numpy as np

a = np.array([45, 23, 56])
a

array([45, 23, 56])

In [ ]:
a.shape # 차원 크기

(3,)

In [ ]:
a.ndim # 차원

1

In [ ]:
a.dtype # 요소의 자료형

dtype('int64')

In [ ]:
a.itemsize # 요소의 크기(바이트)

8

In [ ]:
a.size # 요소의 수

3

In [ ]:
import numpy as np
km = np.array([178, 197, 202, 210])

In [ ]:
km = km + 100
km

array([278, 297, 302, 310])

In [ ]:
import numpy as np
np.arange(0,11,3)

array([0, 3, 6, 9])

In [ ]:
np.arange(0,11,3, dtype=float)

array([0., 3., 6., 9.])

In [ ]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [ ]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(51, 100)

array([ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,  61.,
        62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
        73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,
        84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,
        95.,  96.,  97.,  98.,  99., 100.])

In [ ]:
np.linspace(51, 100, 2)

array([ 51., 100.])

In [ ]:
np.linspace(51, 100, 5)

array([ 51.  ,  63.25,  75.5 ,  87.75, 100.  ])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(2)

array([0.45661364, 0.91625341])

In [ ]:
np.random.rand(2,3)

array([[0.88227938, 0.24866143, 0.26183902],
       [0.54571242, 0.85573747, 0.91870814]])

In [ ]:
np.random.randn(20)

array([-0.65848751,  0.88971706,  1.34319744,  0.72247247,  0.71098458,
       -1.52016567, -1.7651899 ,  0.20001488,  1.02835205, -0.77885681,
        0.61203906,  1.03532436,  0.21914757, -0.56702966,  0.2852159 ,
        0.24145578, -0.60621723,  1.38414106,  0.62284391,  0.38346682])

In [ ]:
np.random.randn(3,3)

array([[-1.68191461,  0.88858653,  0.15675359],
       [ 1.26755946,  1.13189913, -1.56366023],
       [ 1.19203228,  0.66276406,  0.97759641]])

In [ ]:
np.random.randint(1,7) # 1 ~ 6

3

In [ ]:
np.random.randint(1,100, 6)

array([21, 25, 28,  8, 40, 58])

In [ ]:
np.random.randint(1,100, (2,3))

array([[38, 81, 27],
       [25, 20, 56]])

In [ ]:
np.random.randint(1,100, (2,3,3)) # 대괄호 3개 3차원   # 차원 수 , 3행, 3열

array([[[43, 92, 34],
        [94,  4, 44],
        [41, 29, 38]],

       [[63, 95, 30],
        [20, 20, 72],
        [41, 72, 37]]])

In [ ]:
import numpy as np

values = np.random.randn(10)
values

array([-2.22663233, -0.40869896,  1.2910067 , -0.58579477,  0.78280524,
       -1.16115698,  0.40950159,  0.11857048, -1.74136825,  1.3510359 ])

In [ ]:
np.reshape(values, (5,2))

array([[-2.22663233, -0.40869896],
       [ 1.2910067 , -0.58579477],
       [ 0.78280524, -1.16115698],
       [ 0.40950159,  0.11857048],
       [-1.74136825,  1.3510359 ]])

In [ ]:
A = values.max(); B = values.min()
print(A)
print(B)

1.3510359024058398
-2.226632327575812


In [ ]:
C = values.argmax()+1; D = values.argmin()+1
print(C)
print(D)

10
1


In [ ]:
print('Max : {}\nmin: {}\nItem {} is the maximun value, while item {} is the minimum value.'.format (A,B,C,D))

Max : 1.3510359024058398
min: -2.226632327575812
Item 10 is the maximun value, while item 1 is the minimum value.
