In [34]:
# 필요한 라이브러리를 가져옵니다.
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# California Housing 데이터셋을 로드합니다.
housing = fetch_california_housing()
# 데이터와 타겟의 형태를 출력합니다.
print(housing.data.shape, housing.target.shape)
# 특징(feature) 이름을 출력합니다.
print(housing.feature_names)

(20640, 8) (20640,)
['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']


In [35]:
# 데이터를 학습 세트와 테스트 세트로 80:20 비율로 분할합니다.
# 여기서는 'MedInc' (Median Income) 특징만 사용합니다 (첫 번째 열).
X_train, X_test, y_train, y_test = train_test_split(housing.data[:, 0:1], housing.target, test_size=0.2, random_state=42)
# 분할된 데이터 세트의 형태를 출력합니다.
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(16512, 1) (4128, 1) (16512,) (4128,)


In [36]:
# LinearRegression 모델을 초기화합니다.
regr = LinearRegression()
# 학습 데이터를 사용하여 모델을 학습시킵니다.
regr.fit(X_train, y_train)

LinearRegression()

In [37]:
# 학습 데이터에 대한 모델의 R-제곱 점수를 계산하여 출력합니다.
regr.score(X_train, y_train)

0.47699273458205227

In [38]:
# 학습된 선형 회귀 모델의 계수 (기울기)를 출력합니다.
print(regr.coef_)
# 학습된 선형 회귀 모델의 절편을 출력합니다.
print(regr.intercept_)

[0.41933849]
0.4445972916907879


In [39]:
# LinearRegression 모델을 다시 초기화하고 학습시킵니다.
regr = LinearRegression()
regr.fit(X_train, y_train)
# 학습 데이터에 대한 R-제곱 점수를 출력합니다.
print(regr.score(X_train, y_train))

# 테스트 데이터를 사용하여 예측을 수행합니다.
y_pred = regr.predict(X_test)
# 테스트 데이터에 대한 Mean Squared Error (평균 제곱 오차)를 출력합니다.
print(mean_squared_error(y_test, y_pred))

0.47699273458205227
0.7091157771765549


In [40]:
import numpy as np
# 0, 1, 2를 포함하는 1차원 NumPy 배열을 생성합니다.
x = np.arange(3)
# 배열을 출력합니다.
x

array([0, 1, 2])

In [41]:
# 축은 차원이다. 1개면 1차원 2개나오면 2차원 3개면 3차원
# 1차원 배열 x에 새로운 축을 추가하여 2차원 (열 벡터) 배열로 만듭니다.
x[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [44]:
import numpy as np
from sklearn.linear_model import LinearRegression
# 2차원 NumPy 배열을 생성합니다.
x = np.array([[1,1], [1, 2], [2,2], [2,3]]) # Added a second element to the second inner list
# 배열을 출력합니다.
x

array([[1, 1],
       [1, 2],
       [2, 2],
       [2, 3]])

In [45]:
# 2차원 배열 x에 np.newaxis를 사용하여 차원을 확장하는 예제를 보여줍니다.
x[:, np.newaxis]
# 확장된 배열에서 특정 열 (첫 번째 열)을 선택하는 예제를 보여줍니다.
x[:, np.newaxis, 0]

array([[1],
       [1],
       [2],
       [2]])

In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

laliga = pd.read_csv('./drive/MyDrive/laliga.csv')
laliga.head()

,Team,Position,Shirt number,Name,Minutes played,Games played,Percentage of games played,Full games played,Percentage of full games played,Games started,...,Corners,Tackles.1,Duels,Man-to-man duels,Aerial duels,Passes,Short passes,Long passes,Through balls,Goals scored per attempt
0,Athletic Club,Goalkeeper,NaN,Hodei Oleaga,0.000,0,"0,0%",0,"0,0%",0,...,0,0,0,0,0,0.0,0.0,0,0,0
1,Athletic Club,Goalkeeper,1.0,A. Remiro,0.000,0,"0,0%",0,"0,0%",0,...,0,0,0,0,0,0.0,0.0,0,0,0
2,Athletic Club,Goalkeeper,13.0,Herrerín,2.790,31,"82,0%",31,"82,0%",31,...,0,0,25,6,19,887.0,128.0,759,1,0
3,Athletic Club,Goalkeeper,25.0,Unai Simón,630.000,7,"18,0%",7,"18,0%",7,...,0,0,3,2,1,155.0,49.0,106,0,0
4,Athletic Club,Defender,3.0,Núñez,1.063,12,"32,0%",11,"29,0%",11,...,0,15,107,38,69,536.0,457.0,78,1,0
